from setuptools import setup

setup(
    name='gquote',
    version='1.0.0',
    install_requires=['pillow', 'requests'],
    include_package_data=True,
    author="Justxd22",
    author_email="xdjust18@gmail.com",
    url="https://github.com/justxd22/gquote",
    readme = "README.md",
    license = "GPLV3",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "License :: OSI Approved :: GNU GENERAL PUBLIC LICENSE V3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python",
        "Topic :: Internet",
        "Topic :: Multimedia :: Image",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Terminals",
        "Topic :: Utilities",
    ],
    description=("Generate Beautiful quote images"),
    zip_safe=True,
    python_requires=">=3.6",
    project_urls={"Github": "https://github.com/justxd22/gquote"},
    keywords=["quotes", "png", "images", "pillow", "generate"],
)
